[tool.poetry]
name = "workaround-for-editable-install"
version = "0.0.1"
description = ""
authors = ["none"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
kserve = { path = "../python/kserve", develop = false }
sklearnserver = { path = "../python/paddleserver", develop = false }

